# Generated by Django 3.1.2 on 2020-11-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['id_number']},
        ),
    ]
