# Generated by Django 3.1.4 on 2020-12-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20201206_2327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['patient_id']},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='surname',
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Patient Id'),
        ),
    ]
