# Generated by Django 3.1.4 on 2020-12-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20201206_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(default='', max_length=50, verbose_name='Patient Id'),
        ),
    ]
