# Generated by Django 3.1.4 on 2020-12-07 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_auto_20201207_0902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['user__id_no']},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_id',
        ),
    ]
