# Generated by Django 3.1.2 on 2020-11-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnoses', '0005_auto_20201118_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='date',
            field=models.DateField(verbose_name=' Date (YY-MM-DD)'),
        ),
    ]
