# Generated by Django 3.1.2 on 2020-11-18 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnoses', '0006_auto_20201118_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='by_specialist_nurse',
        ),
    ]
