# Generated by Django 3.1.4 on 2020-12-07 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnoses', '0008_diagnosis_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='user',
        ),
    ]
